### Register User

POST http://localhost:3000/api/v1/auth/register
content-type: application/json

{
  "firstName": "test",
  "lastName": "1",
  "email": "demo@email.com",
  "password": "Admin123*"
}

### Login User

POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "email": "demo@email.com",
  "password": "Admin123*"
}

### Logout User

GET http://localhost:3000/api/v1/auth/logout
content-type: application/json

### Profile

GET http://localhost:3000/api/v1/auth/me
content-type: application/json
Authorization: Bearer paste_token_here
### Update Profile

PUT http://localhost:3000/api/v1/auth/updateDetails
content-type: application/json
Authorization: Bearer paste_token_here
{
  "firstName": "test",
  "lastName": "1",
  "imageUrl": "test.png"

}

### Update User Password

PUT http://localhost:3000/api/v1/auth/updatePassword
content-type: application/json
Authorization: Bearer paste_token_here
{
  "currentPassword": "123456",
  "newPassword": "1234567"

}

### Forgot Password

POST http://localhost:3000/api/v1/auth/forgotPassword
content-type: application/json

{
  "email": "demo@email.com"
}

### Reset Password

PUT http://localhost:3000/api/v1/auth/resetPassword/:resetToken
content-type: application/json

{
  "password": "newpassword"
}

### Add Sheet

POST http://localhost:3000/api/v1/sheets/
content-type: application/json
Authorization: Bearer paste_token_here

{
  "description": "1234",
  "title": "demo"
}

### Update Sheet

PUT http://localhost:3000/api/v1/sheets/63bd7964bc34fa5d38c4dbed
content-type: application/json
Authorization: Bearer paste_token_here

{
  "description": "1234",
  "title": "Updated Sheet"
}

### Get all Sheets

GET http://localhost:3000/api/v1/sheets/
content-type: application/json
Authorization: Bearer paste_token_here

### Get Sheet by id

GET http://localhost:3000/api/v1/sheets/63bd7964bc34fa5d38c4dbed
content-type: application/json
Authorization: Bearer paste_token_here

### Delete Sheet by id

DELETE http://localhost:3000/api/v1/sheets/63bd7964bc34fa5d38c4dbed
content-type: application/json
Authorization: Bearer paste_token_here
